package cmy.android_jk_new.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cmy.android_jk_new.bean.LoginUser;
import cmy.android_jk_new.bean.BankInfo;

import cmy.android_jk_new.greendao.LoginUserDao;
import cmy.android_jk_new.greendao.BankInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginUserDaoConfig;
    private final DaoConfig bankInfoDaoConfig;

    private final LoginUserDao loginUserDao;
    private final BankInfoDao bankInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginUserDaoConfig = daoConfigMap.get(LoginUserDao.class).clone();
        loginUserDaoConfig.initIdentityScope(type);

        bankInfoDaoConfig = daoConfigMap.get(BankInfoDao.class).clone();
        bankInfoDaoConfig.initIdentityScope(type);

        loginUserDao = new LoginUserDao(loginUserDaoConfig, this);
        bankInfoDao = new BankInfoDao(bankInfoDaoConfig, this);

        registerDao(LoginUser.class, loginUserDao);
        registerDao(BankInfo.class, bankInfoDao);
    }
    
    public void clear() {
        loginUserDaoConfig.clearIdentityScope();
        bankInfoDaoConfig.clearIdentityScope();
    }

    public LoginUserDao getLoginUserDao() {
        return loginUserDao;
    }

    public BankInfoDao getBankInfoDao() {
        return bankInfoDao;
    }

}
