package com.hlct.android.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hlct.android.bean.BankInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BANK_INFO".
*/
public class BankInfoDao extends AbstractDao<BankInfo, Long> {

    public static final String TABLENAME = "BANK_INFO";

    /**
     * Properties of entity BankInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property BankId = new Property(0, Long.class, "bankId", true, "_id");
        public final static Property BankName = new Property(1, String.class, "bankName", false, "BANK_NAME");
        public final static Property LineId = new Property(2, String.class, "lineId", false, "LINE_ID");
        public final static Property BankTaskStatus = new Property(3, String.class, "bankTaskStatus", false, "BANK_TASK_STATUS");
    }


    public BankInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BankInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BANK_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY UNIQUE ," + // 0: bankId
                "\"BANK_NAME\" TEXT NOT NULL ," + // 1: bankName
                "\"LINE_ID\" TEXT," + // 2: lineId
                "\"BANK_TASK_STATUS\" TEXT);"); // 3: bankTaskStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BANK_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BankInfo entity) {
        stmt.clearBindings();
 
        Long bankId = entity.getBankId();
        if (bankId != null) {
            stmt.bindLong(1, bankId);
        }
        stmt.bindString(2, entity.getBankName());
 
        String lineId = entity.getLineId();
        if (lineId != null) {
            stmt.bindString(3, lineId);
        }
 
        String bankTaskStatus = entity.getBankTaskStatus();
        if (bankTaskStatus != null) {
            stmt.bindString(4, bankTaskStatus);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BankInfo entity) {
        stmt.clearBindings();
 
        Long bankId = entity.getBankId();
        if (bankId != null) {
            stmt.bindLong(1, bankId);
        }
        stmt.bindString(2, entity.getBankName());
 
        String lineId = entity.getLineId();
        if (lineId != null) {
            stmt.bindString(3, lineId);
        }
 
        String bankTaskStatus = entity.getBankTaskStatus();
        if (bankTaskStatus != null) {
            stmt.bindString(4, bankTaskStatus);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BankInfo readEntity(Cursor cursor, int offset) {
        BankInfo entity = new BankInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // bankId
            cursor.getString(offset + 1), // bankName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lineId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // bankTaskStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BankInfo entity, int offset) {
        entity.setBankId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBankName(cursor.getString(offset + 1));
        entity.setLineId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBankTaskStatus(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BankInfo entity, long rowId) {
        entity.setBankId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BankInfo entity) {
        if(entity != null) {
            return entity.getBankId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BankInfo entity) {
        return entity.getBankId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
