package com.hlct.android.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hlct.android.bean.BankInfo;
import com.hlct.android.bean.LoginUser;

import com.hlct.android.greendao.BankInfoDao;
import com.hlct.android.greendao.LoginUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bankInfoDaoConfig;
    private final DaoConfig loginUserDaoConfig;

    private final BankInfoDao bankInfoDao;
    private final LoginUserDao loginUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bankInfoDaoConfig = daoConfigMap.get(BankInfoDao.class).clone();
        bankInfoDaoConfig.initIdentityScope(type);

        loginUserDaoConfig = daoConfigMap.get(LoginUserDao.class).clone();
        loginUserDaoConfig.initIdentityScope(type);

        bankInfoDao = new BankInfoDao(bankInfoDaoConfig, this);
        loginUserDao = new LoginUserDao(loginUserDaoConfig, this);

        registerDao(BankInfo.class, bankInfoDao);
        registerDao(LoginUser.class, loginUserDao);
    }
    
    public void clear() {
        bankInfoDaoConfig.clearIdentityScope();
        loginUserDaoConfig.clearIdentityScope();
    }

    public BankInfoDao getBankInfoDao() {
        return bankInfoDao;
    }

    public LoginUserDao getLoginUserDao() {
        return loginUserDao;
    }

}
