package com.hlct.android.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hlct.android.bean.BankInfo;
import com.hlct.android.bean.Detail;
import com.hlct.android.bean.LoginUser;
import com.hlct.android.bean.PlanBean;
import com.hlct.android.bean.User;

import com.hlct.android.greendao.BankInfoDao;
import com.hlct.android.greendao.DetailDao;
import com.hlct.android.greendao.LoginUserDao;
import com.hlct.android.greendao.PlanBeanDao;
import com.hlct.android.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bankInfoDaoConfig;
    private final DaoConfig detailDaoConfig;
    private final DaoConfig loginUserDaoConfig;
    private final DaoConfig planBeanDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BankInfoDao bankInfoDao;
    private final DetailDao detailDao;
    private final LoginUserDao loginUserDao;
    private final PlanBeanDao planBeanDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bankInfoDaoConfig = daoConfigMap.get(BankInfoDao.class).clone();
        bankInfoDaoConfig.initIdentityScope(type);

        detailDaoConfig = daoConfigMap.get(DetailDao.class).clone();
        detailDaoConfig.initIdentityScope(type);

        loginUserDaoConfig = daoConfigMap.get(LoginUserDao.class).clone();
        loginUserDaoConfig.initIdentityScope(type);

        planBeanDaoConfig = daoConfigMap.get(PlanBeanDao.class).clone();
        planBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bankInfoDao = new BankInfoDao(bankInfoDaoConfig, this);
        detailDao = new DetailDao(detailDaoConfig, this);
        loginUserDao = new LoginUserDao(loginUserDaoConfig, this);
        planBeanDao = new PlanBeanDao(planBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(BankInfo.class, bankInfoDao);
        registerDao(Detail.class, detailDao);
        registerDao(LoginUser.class, loginUserDao);
        registerDao(PlanBean.class, planBeanDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        bankInfoDaoConfig.clearIdentityScope();
        detailDaoConfig.clearIdentityScope();
        loginUserDaoConfig.clearIdentityScope();
        planBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public BankInfoDao getBankInfoDao() {
        return bankInfoDao;
    }

    public DetailDao getDetailDao() {
        return detailDao;
    }

    public LoginUserDao getLoginUserDao() {
        return loginUserDao;
    }

    public PlanBeanDao getPlanBeanDao() {
        return planBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
